# Generated by Django 5.0.6 on 2024-07-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(upload_to='shop/category/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='shop',
            name='speciality',
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(upload_to='shop/category/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.ManyToManyField(to='shop.category'),
        ),
        migrations.DeleteModel(
            name='Speciality',
        ),
    ]
