# Generated by Django 5.0.6 on 2024-07-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_remove_shop_speciality_alter_shop_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(null=True, upload_to='shop/shop/'),
        ),
    ]
