# Generated by Django 5.0.6 on 2024-07-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shop_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='shop/shop_detail/')),
                ('price', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(to='shop.category')),
            ],
        ),
    ]
