# Generated by Django 5.0.6 on 2024-07-22 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shop_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop_Detail',
        ),
    ]
