# Generated by Django 4.2.14 on 2024-07-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(default=1, upload_to='cart/'),
            preserve_default=False,
        ),
    ]
